language: node_js
node_js:
  - "4.2"
<<<<<<< HEAD
branches:
  only:
   - test/signupFunctionalTest
=======
>>>>>>> inwin/dev
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
    package:
     - g++-4.8
cache:
  directories:
   - node_modules
